### ISSUE TITLE
msys2 symlinks error

### ISSUE THREAD

**Issue by v98765** [ansible-collections/cisco.nxos#162]
##### SUMMARY
cant install on win64 

##### ISSUE TYPE
"Create symbolic links" privilege required
https://stackoverflow.com/questions/6260149/os-symlink-support-in-windows/8464306#8464306

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.1
  config file = None
  configured module search path = ['/home/v98765/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 27 2020, 21:53:06) [GCC 9.3.0]
```

##### OS / ENVIRONMENT

windows 2012 r2
user account

##### STEPS TO REPRODUCE
install msys2 and ansible
```sh
$ pacman -S python3-pip
$ pip3 install --upgrade pip
$ pacman -S gcc make libffi-devel openssl-devel libcrypt-devel
$ pacman -S sshpass
$ pip install wheel
$ pip install ansible
$ ansible-galaxy collection install ansible.netcommon
$ ansible-galaxy collection install cisco.nxos
```

##### EXPECTED RESULTS

nxos modules installed

##### ACTUAL RESULTS

````text
v98765@MSYS ~
$ ansible-galaxy collection install cisco.nxos -vvv
ansible-galaxy 2.10.1
  config file = None
  configured module search path = ['/home/v98765/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.8.5 (default, Aug 27 2020, 21:53:06) [GCC 9.3.0]
No config file found; using defaults
Starting galaxy collection install process
Found installed collection ansible.netcommon:1.2.1 at '/home/v98765/.ansible/collections/ansible_collections/ansible/netcommon'
Process install dependency map
Opened /home/v98765/.ansible/galaxy_token
Processing requirement collection 'cisco.nxos'
Collection 'cisco.nxos' obtained from server default https://galaxy.ansible.com/api/
Processing requirement collection 'ansible.netcommon' - as dependency of cisco.nxos
Collection 'ansible.netcommon' obtained from server default https://galaxy.ansible.com/api/
Starting collection install process
Installing 'cisco.nxos:1.1.0' to '/home/v98765/.ansible/collections/ansible_collections/cisco/nxos'
Downloading https://galaxy.ansible.com/download/cisco-nxos-1.1.0.tar.gz to /home/v98765/.ansible/tmp/ansible-local-48355wze83y81/tmpmarqer9c
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: b'storage/nxos_devicealias.py' -> b'/home/v98765/.ansible/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_devicealias.py'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 490, in run
    context.CLIARGS['func']()
  File "/usr/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 1057, in execute_install
    self._execute_install_collection(collection_requirements, collection_path)
  File "/usr/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 1078, in _execute_install_collection
    install_collections(requirements, output_path, self.api_servers, (not ignore_certs), ignore_errors,
  File "/usr/lib/python3.8/site-packages/ansible/galaxy/collection.py", line 695, in install_collections
    collection.install(output_path, b_temp_path)
  File "/usr/lib/python3.8/site-packages/ansible/galaxy/collection.py", line 250, in install
    self.install_artifact(b_collection_path, b_temp_path)
  File "/usr/lib/python3.8/site-packages/ansible/galaxy/collection.py", line 273, in install_artifact
    _extract_tar_file(collection_tar, file_name, b_collection_path, b_temp_path,
  File "/usr/lib/python3.8/site-packages/ansible/galaxy/collection.py", line 1477, in _extract_tar_file
    os.symlink(b_link_path, b_dest_filepath)
FileNotFoundError: [Errno 2] No such file or directory: b'storage/nxos_devicealias.py' -> b'/home/v98765/.ansible/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_devicealias.py'

v98765@ MSYS ~
```

**Comment by NilashishC** [comment]
Hi @v98765!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This issue is not specific to this collection (will happen with any collection that has module symlinks) and appears to be something that should be filed against [ansible/ansible](github.com/ansible/ansible) so that the concerned team can look at it.

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

https://groups.google.com/forum/#!forum/ansible-project
https://groups.google.com/forum/#!forum/ansible-devel
We'd be happy to discuss things.

Thank you once again!
