### ISSUE TITLE
cisco.nxos.nxos_bgp_neighbor_address_family; send_community fails when already set.

### ISSUE THREAD

**Issue by pahansson** [ansible-collections/cisco.nxos#281]
##### SUMMARY
cisco.nxos.nxos_bgp_neighbor_address_family; send_community fails when already set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_bgp_neighbor_address_family

##### ANSIBLE VERSION
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Note:
  Running python3 with; ansible_python_interpreter: /usr/bin/python3
  /usr/bin/python3 --version
  Python 3.6.8

##### CONFIGURATION

<nothing>

##### OS / ENVIRONMENT

Linux xxx-xxxxx 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
Works when communities isn't configured.
Fails when running the below role when communities already configured on router.

```
    - name: Configure BGP neighbor address family
      cisco.nxos.nxos_bgp_neighbor_address_family:
        config:
          neighbors:
          - neighbor_address: '{{ item.ip }}'
            address_family:
#              - afi: ipv4
#                safi: unicast
              - afi: l2vpn
                safi: evpn
                route_reflector_client: '{{ item.rr_client }}'
                send_community:
                  both: yes
        state: merged
      loop: '{{ bgp_neighbors }}'
      when: ansible_network_os == 'cisco.nxos.nxos'

```

##### EXPECTED RESULTS
Play to go through without failing.

##### ACTUAL RESULTS
Play fails. Also fails if using; standard: yes
Works if only using extended: yes

Looks like module is always using send-community extended;

ansible.module_utils.connection.ConnectionError: send-community extended both
                                                                     ^
% Invalid command at '^' marker.

```
TASK [bgp_neighbors : Configure BGP neighbor address family] **************************************************************************************************************************************************************
task path: /xxxx/bgp_neighbors/tasks/main.yml:27
<x.x.x.x> attempting to start connection
<x.x.x.x> using connection plugin ansible.netcommon.network_cli
<x.x.x.x> found existing local domain socket, using it!
<x.x.x.x> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<x.x.x.x> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<x.x.x.x> updating play_context for connection
<x.x.x.x> 
<x.x.x.x> local domain socket path is /home/xxxx/.ansible/pc/a71c1f00b8
<x.x.x.x> Using network group action cisco.nxos.nxos for cisco.nxos.nxos_bgp_neighbor_address_family
<x.x.x.x> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<x.x.x.x> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<x.x.x.x> ANSIBLE_NETWORK_IMPORT_MODULES: disabled for when not Python 3
<x.x.x.x> ESTABLISH LOCAL CONNECTION FOR USER: xxxx
<x.x.x.x> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht `"&& mkdir "` echo /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271 `" && echo ansible-tmp-1617967641.36-110655-146281993767271="` echo /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271 `" ) && sleep 0'
Using module file /awxprojects/NS/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_bgp_neighbor_address_family.py
<x.x.x.x> PUT /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/tmpBvwRQ4 TO /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/AnsiballZ_nxos_bgp_neighbor_address_family.py
<x.x.x.x> EXEC /bin/sh -c 'chmod u+x /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/ /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/AnsiballZ_nxos_bgp_neighbor_address_family.py && sleep 0'
<x.x.x.x> EXEC /bin/sh -c '/usr/bin/python3 /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/AnsiballZ_nxos_bgp_neighbor_address_family.py && sleep 0'
<x.x.x.x> EXEC /bin/sh -c 'rm -f -r /home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/AnsiballZ_nxos_bgp_neighbor_address_family.py", line 102, in <module>
    _ansiballz_main()
  File "/home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/AnsiballZ_nxos_bgp_neighbor_address_family.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/xxxx/.ansible/tmp/ansible-local-110542aUVlht/ansible-tmp-1617967641.36-110655-146281993767271/AnsiballZ_nxos_bgp_neighbor_address_family.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_bgp_neighbor_address_family', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload_58n2zcs4/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_bgp_neighbor_address_family.py", line 1152, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload_58n2zcs4/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_bgp_neighbor_address_family.py", line 1147, in main
  File "/tmp/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload_58n2zcs4/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/config/bgp_neighbor_address_family/bgp_neighbor_address_family.py", line 88, in execute_module
  File "/tmp/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload_58n2zcs4/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/rm_base/resource_module.py", line 154, in run_commands
  File "/tmp/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload_58n2zcs4/ansible_cisco.nxos.nxos_bgp_neighbor_address_family_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: send-community extended both
                                                                     ^
% Invalid command at '^' marker.
XXXXX-LF04(config-router-neighbor-af)# 
failed: [x.x.x.x] (item={u'ip': u'x.x.x.x', u'desc': u'XXXXX-SP01', u'rr_client': False}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": {
        "desc": "XXXXX-SP01", 
        "ip": "x.x.x.x", 
        "rr_client": false
    },
```

**Comment by NilashishC** [comment]
@pahansson Thank you for reporting this issue. This should be fixed by the patch in #291.
