### ISSUE TITLE
cisco.nxos.nxos_pim_interface module error 

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#294]
##### SUMMARY
cisco.nxos.nxos_pim_interface errors when configuring interfaces 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_pim_interface

##### ANSIBLE VERSION
ansible 2.10.4
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /home/feisa/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION
```yaml
- name: Configure PIM on Interfaces
  cisco.nxos.nxos_pim_interface:
    interface: "{{ item.interface }}"
    sparse: true
    bfd: enable
  when: item.pim is defined
  with_items: 
    - "{{ layer3_ports }}"
  tags:
    - nxos-pim  
 ```
From my var file
layer3_ports: 
  - { interface: loopback0,    ipv4: 10.4.255.1/32,  ospf_cost: 1, area_id: 4 }
  - { interface: Ethernet1/39, ipv4: 10.4.254.51/29, ospf_cost: 2, area_id: 0, passive: no, ospf_hello: 1, ospf_dead: 4, network_type: broadcast, pim: true, bfd: disable, desc: 'ch1-firec001 e1/15' }
  - { interface: Ethernet1/40, ipv4: 10.4.254.59/29, ospf_cost: 5, area_id: 0, passive: no, ospf_hello: 1, ospf_dead: 4, network_type: broadcast, pim: true, bfd: disable, desc: 'ch1-firec002 e1/16' }  
  - { interface: Vlan66,       ipv4: 10.151.161.65/27, des: External-Primary, area_id: 4, pim: true }
##### STEPS TO REPRODUCE
run the role above 
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->


##### ACTUAL RESULTS
The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 637, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 598, in main
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 328, in get_pim_interface
AttributeError: 'NoneType' object has no attribute 'group'
failed: [tc1-spinc001] (item={'interface': 'Ethernet1/39', 'ipv4': '10.4.254.51/29', 'ospf_cost': 2, 'area_id': 0, 'passive': False, 'ospf_hello': 1, 'ospf_dead': 4, 'network_type': 'broadcast', 'pim': True, 'bfd': 'disable'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "area_id": 0,
        "bfd": "disable",
        "interface": "Ethernet1/39",
        "ipv4": "10.4.254.51/29",
        "network_type": "broadcast",
        "ospf_cost": 2,
        "ospf_dead": 4,
        "ospf_hello": 1,
        "passive": false,
        "pim": true
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 637, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 598, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 328, in get_pim_interface\nAttributeError: 'NoneType' object has no attribute 'group'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
Trying secret FileVaultSecret(filename='/home/feisa/ansible-network/vault-id') for vault_id=default
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
<tc1-spinc001> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<tc1-spinc001> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<tc1-spinc001> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed `"&& mkdir "` echo /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260 `" && echo ansible-tmp-1620333601.8236308-1605049-262891294756260="` echo /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260 `" ) && sleep 0'
Using module file /home/feisa/ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py
<tc1-spinc001> PUT /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/tmp01qupkx6 TO /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py
<tc1-spinc001> EXEC /bin/sh -c 'chmod u+x /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/ /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py && sleep 0'
<tc1-spinc001> EXEC /bin/sh -c '/usr/libexec/platform-python /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py && sleep 0'
<tc1-spinc001> EXEC /bin/sh -c 'rm -f -r /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 637, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 598, in main
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 328, in get_pim_interface
AttributeError: 'NoneType' object has no attribute 'group'
failed: [tc1-spinc001] (item={'interface': 'Ethernet1/40', 'ipv4': '10.4.254.59/29', 'ospf_cost': 5, 'area_id': 0, 'passive': False, 'ospf_hello': 1, 'ospf_dead': 4, 'network_type': 'broadcast', 'pim': True, 'bfd': 'disable'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "area_id": 0,
        "bfd": "disable",
        "interface": "Ethernet1/40",
        "ipv4": "10.4.254.59/29",
        "network_type": "broadcast",
        "ospf_cost": 5,
        "ospf_dead": 4,
        "ospf_hello": 1,
        "passive": false,
        "pim": true
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 637, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 598, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 328, in get_pim_interface\nAttributeError: 'NoneType' object has no attribute 'group'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by NilashishC** [comment]
@feisa Which NX-OS version is the target device running?

**Comment by NilashishC** [comment]
@feisa Since we haven't heard from you yet and we were not able to reproduce this issue on our end with multiple NX-OS versions, we'll be closing this ticket for now. If you continue to face this issue, feel free to re-open this ticket and we'll look into it. Thank you for your interest in Ansible!

**Comment by feisacrabel** [comment]
@NilashishC can you please reopen this case?

**Comment by feisacrabel** [comment]
Software
  BIOS: version 07.68
 NXOS: version 9.3(6)
  BIOS compile time:  05/18/2020
  NXOS image file is: bootflash:///nxos.9.3.6.bin
