### ISSUE TITLE
cisco.nxos.nxos_facts broken in v2.5.1

### ISSUE THREAD

**Issue by ChristopherJHart** [ansible-collections/cisco.nxos#364]
##### SUMMARY

The cisco.nxos.nxos_facts module throws a KeyError traceback in v2.5.1. This same module works fine on v.2.5.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_facts

##### ANSIBLE VERSION

```
ansible 2.10.4
  config file = /home/christopher/Documents/Ansible/facts-bug/ansible.cfg
  configured module search path = ['/home/christopher/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/christopher/Documents/Ansible/facts-bug/venv/lib/python3.8/site-packages/ansible
  executable location = /home/christopher/Documents/Ansible/facts-bug/venv/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

##### COLLECTION VERSION

```
# /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 2.5.1  
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/christopher/Documents/Ansible/facts-bug/ansible.cfg) = ['/home/christopher/Documents/Ansible/facts-bug/collections']
HOST_KEY_CHECKING(/home/christopher/Documents/Ansible/facts-bug/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Reproduced on live hardware (several different models of NX-OS running 9.3(x), 10.1(x), and 10.2(x)) as well as a 9000v running NX-OS 9.3(7).

##### STEPS TO REPRODUCE
Run the following command against a 9000v with v2.5.1 installed:
```
ansible -i <INVENTORY-HERE> -m cisco.nxos.nxos_facts <HOST-HERE>
```
When this command is run, the following error appears:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'interface'
[DEPRECATION WARNING]: Distribution ubuntu 20.04 on host 192.168.30.114 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
192.168.30.114 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/christopher/.ansible/tmp/ansible-local-2731405e8xprhah/ansible-tmp-1632330684.257702-2731413-38172443755113/AnsiballZ_nxos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/christopher/.ansible/tmp/ansible-local-2731405e8xprhah/ansible-tmp-1632330684.257702-2731413-38172443755113/AnsiballZ_nxos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/christopher/.ansible/tmp/ansible-local-2731405e8xprhah/ansible-tmp-1632330684.257702-2731413-38172443755113/AnsiballZ_nxos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_u9f4tenz/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 259, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_u9f4tenz/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 250, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_u9f4tenz/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 161, in get_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_u9f4tenz/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 162, in get_network_legacy_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_u9f4tenz/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 255, in populate\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_u9f4tenz/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 348, in populate_structured_neighbors_cdp\nKeyError: 'interface'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

##### EXPECTED RESULTS

NX-OS facts should be gathered as expected.

##### ACTUAL RESULTS
Verbose output is below:
```
$ ansible -i inventory.yaml -m cisco.nxos.nxos_facts 192.168.30.114 -vvvv
ansible 2.10.4
  config file = /home/christopher/Documents/Ansible/facts-bug/ansible.cfg
  configured module search path = ['/home/christopher/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/christopher/Documents/Ansible/facts-bug/venv/lib/python3.8/site-packages/ansible
  executable location = /home/christopher/Documents/Ansible/facts-bug/venv/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
Using /home/christopher/Documents/Ansible/facts-bug/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/christopher/Documents/Ansible/facts-bug/inventory.yaml as it did not pass its verify_file() method
script declined parsing /home/christopher/Documents/Ansible/facts-bug/inventory.yaml as it did not pass its verify_file() method
Parsed /home/christopher/Documents/Ansible/facts-bug/inventory.yaml inventory source with yaml plugin
Loading callback plugin minimal of type stdout, v2.0 from /home/christopher/Documents/Ansible/facts-bug/venv/lib/python3.8/site-packages/ansible/plugins/callback/minimal.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
META: ran handlers
Loading collection cisco.nxos from /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections/cisco/nxos
redirecting (type: action) cisco.nxos.nxos_facts to cisco.nxos.nxos
Loading collection ansible.netcommon from /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections/ansible/netcommon
<192.168.30.114> attempting to start connection
<192.168.30.114> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /home/christopher/Documents/Ansible/facts-bug/venv/bin/ansible-connection
<192.168.30.114> local domain socket does not exist, starting it
<192.168.30.114> control socket path is /home/christopher/.ansible/pc/d9f9afb870
<192.168.30.114> Loading collection ansible.netcommon from /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections/ansible/netcommon
<192.168.30.114> Loading collection cisco.nxos from /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections/cisco/nxos
<192.168.30.114> local domain socket listeners started successfully
<192.168.30.114> loaded cliconf plugin ansible_collections.cisco.nxos.plugins.cliconf.nxos from path /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections/cisco/nxos/plugins/cliconf/nxos.py for network_os cisco.nxos.nxos
<192.168.30.114> ssh type is set to paramiko
<192.168.30.114> 
<192.168.30.114> local domain socket path is /home/christopher/.ansible/pc/d9f9afb870
redirecting (type: action) cisco.nxos.nxos_facts to cisco.nxos.nxos
redirecting (type: action) cisco.nxos.nxos_facts to cisco.nxos.nxos
<192.168.30.114> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<192.168.30.114> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<192.168.30.114> ESTABLISH LOCAL CONNECTION FOR USER: christopher
<192.168.30.114> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6 `"&& mkdir "` echo /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712 `" && echo ansible-tmp-1632331003.8157113-2733786-105637168297712="` echo /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712 `" ) && sleep 0'
<192.168.30.114> Attempting python interpreter discovery
<192.168.30.114> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.30.114> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/christopher/Documents/Ansible/facts-bug/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py
<192.168.30.114> PUT /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/tmp_o_au2yb TO /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py
<192.168.30.114> EXEC /bin/sh -c 'chmod u+x /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/ /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py && sleep 0'
<192.168.30.114> EXEC /bin/sh -c '/usr/bin/python /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py && sleep 0'
<192.168.30.114> EXEC /bin/sh -c 'rm -f -r /home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py", line 259, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py", line 250, in main
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py", line 161, in get_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 162, in get_network_legacy_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py", line 255, in populate
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py", line 348, in populate_structured_neighbors_cdp
KeyError: 'interface'
[DEPRECATION WARNING]: Distribution ubuntu 20.04 on host 192.168.30.114 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
192.168.30.114 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/christopher/.ansible/tmp/ansible-local-27337715deb7cd6/ansible-tmp-1632331003.8157113-2733786-105637168297712/AnsiballZ_nxos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 259, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 250, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 161, in get_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 162, in get_network_legacy_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 255, in populate\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_bpe6jgc2/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 348, in populate_structured_neighbors_cdp\nKeyError: 'interface'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by NilashishC** [comment]
@ChristopherJHart This has been fixed in the latest code and will a part of the upcoming monthly release.
Here's the related PR: https://github.com/ansible-collections/cisco.nxos/pull/358.

Thanks!
