### ISSUE TITLE
NXOS PIM module

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#463]
SUMMARY
cisco.nxos.nxos_pim_interface errors when configuring interfaces

ISSUE TYPE
Bug Report
COMPONENT NAME
cisco.nxos.nxos_pim_interface

ANSIBLE VERSION
ansible 2.10.4
config file = /home/feisa/ansible-network/ansible.cfg
configured module search path = ['/home/feisa/ansible-network/library']
ansible python module location = /home/feisa/.local/lib/python3.6/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

CONFIGURATION
- name: Configure PIM on Interfaces
  cisco.nxos.nxos_pim_interface:
    interface: "{{ item.interface }}"
    sparse: true
    bfd: enable
  when: item.pim is defined
  with_items: 
    - "{{ layer3_ports }}"
  tags:
    - nxos-pim  
From my var file
layer3_ports:

{ interface: loopback0, ipv4: 10.4.255.1/32, ospf_cost: 1, area_id: 4 }
{ interface: Ethernet1/39, ipv4: 10.4.254.51/29, ospf_cost: 2, area_id: 0, passive: no, ospf_hello: 1, ospf_dead: 4, network_type: broadcast, pim: true, bfd: disable, desc: 'ch1-firec001 e1/15' }
{ interface: Ethernet1/40, ipv4: 10.4.254.59/29, ospf_cost: 5, area_id: 0, passive: no, ospf_hello: 1, ospf_dead: 4, network_type: broadcast, pim: true, bfd: disable, desc: 'ch1-firec002 e1/16' }
{ interface: Vlan66, ipv4: 10.151.161.65/27, des: External-Primary, area_id: 4, pim: true }
OS / ENVIRONMENT
STEPS TO REPRODUCE
run the role above

##### ACTUAL RESULTS
The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 637, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 598, in main
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 328, in get_pim_interface
AttributeError: 'NoneType' object has no attribute 'group'
failed: [tc1-spinc001] (item={'interface': 'Ethernet1/39', 'ipv4': '10.4.254.51/29', 'ospf_cost': 2, 'area_id': 0, 'passive': False, 'ospf_hello': 1, 'ospf_dead': 4, 'network_type': 'broadcast', 'pim': True, 'bfd': 'disable'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "area_id": 0,
        "bfd": "disable",
        "interface": "Ethernet1/39",
        "ipv4": "10.4.254.51/29",
        "network_type": "broadcast",
        "ospf_cost": 2,
        "ospf_dead": 4,
        "ospf_hello": 1,
        "passive": false,
        "pim": true
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333600.3746307-1605049-159268183663480/AnsiballZ_nxos_pim_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 637, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 598, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_njgwtpup/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 328, in get_pim_interface\nAttributeError: 'NoneType' object has no attribute 'group'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
Trying secret FileVaultSecret(filename='/home/feisa/ansible-network/vault-id') for vault_id=default
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
<tc1-spinc001> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<tc1-spinc001> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<tc1-spinc001> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed `"&& mkdir "` echo /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260 `" && echo ansible-tmp-1620333601.8236308-1605049-262891294756260="` echo /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260 `" ) && sleep 0'
Using module file /home/feisa/ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py
<tc1-spinc001> PUT /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/tmp01qupkx6 TO /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py
<tc1-spinc001> EXEC /bin/sh -c 'chmod u+x /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/ /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py && sleep 0'
<tc1-spinc001> EXEC /bin/sh -c '/usr/libexec/platform-python /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py && sleep 0'
<tc1-spinc001> EXEC /bin/sh -c 'rm -f -r /home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 637, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 598, in main
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 328, in get_pim_interface
AttributeError: 'NoneType' object has no attribute 'group'
failed: [tc1-spinc001] (item={'interface': 'Ethernet1/40', 'ipv4': '10.4.254.59/29', 'ospf_cost': 5, 'area_id': 0, 'passive': False, 'ospf_hello': 1, 'ospf_dead': 4, 'network_type': 'broadcast', 'pim': True, 'bfd': 'disable'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "area_id": 0,
        "bfd": "disable",
        "interface": "Ethernet1/40",
        "ipv4": "10.4.254.59/29",
        "network_type": "broadcast",
        "ospf_cost": 5,
        "ospf_dead": 4,
        "ospf_hello": 1,
        "passive": false,
        "pim": true
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-16039056ruxy5ed/ansible-tmp-1620333601.8236308-1605049-262891294756260/AnsiballZ_nxos_pim_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 637, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 598, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_qv_0jhbd/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 328, in get_pim_interface\nAttributeError: 'NoneType' object has no attribute 'group'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by feisa** [comment]
@NilashishC bumping for visability

**Comment by rozmusjs** [comment]
@NilashishC , can you please retest this against Vlan and physical interfaces?
The logic configuration works for a Vlan interface, not for the physical interface.
Please see the below output:

Working config (Vlan):
--------------------------
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fec55768978> for vault_id=default
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fec55768978> for vault_id=default
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
<tc1-spinc002> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<tc1-spinc002> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<tc1-spinc002> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3 `"&& mkdir "` echo /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansi                                                                            ble-tmp-1656427574.6636217-4152848-245840705847804 `" && echo ansible-tmp-1656427574.6636217-4152848-245840705847804="` echo /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-165642                                                                            7574.6636217-4152848-245840705847804 `" ) && sleep 0'
Using module file /home/jrozmus/ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py
<tc1-spinc002> PUT /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/tmpbbrl7smm TO /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427574.6636217-4152848-2458407058478                                                                            04/AnsiballZ_nxos_pim_interface.py
<tc1-spinc002> EXEC /bin/sh -c 'chmod u+x /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427574.6636217-4152848-245840705847804/ /home/jrozmus/.ansible/tmp/ansible-local-4152                                                                            362_3hya1a3/ansible-tmp-1656427574.6636217-4152848-245840705847804/AnsiballZ_nxos_pim_interface.py && sleep 0'
<tc1-spinc002> EXEC /bin/sh -c '/usr/libexec/platform-python /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427574.6636217-4152848-245840705847804/AnsiballZ_nxos_pim_interfac                                                                            e.py && sleep 0'
<tc1-spinc002> EXEC /bin/sh -c 'rm -f -r /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427574.6636217-4152848-245840705847804/ > /dev/null 2>&1 && sleep 0'
ok: [tc1-spinc002] => (item={'interface': 'Vlan99', 'ipv4': '10.151.164.97/27', 'des': 'External-Secondary', 'area_id': 4, 'pim': True}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "bfd": "enable",
            "border": false,
            "dr_prio": null,
            "hello_auth_key": null,
            "hello_interval": null,
            "hello_interval_ms": null,
            "interface": "Vlan99",
            "jp_policy_in": null,
            "jp_policy_out": null,
            "jp_type_in": null,
            "jp_type_out": null,
            "neighbor_policy": null,
            "neighbor_type": null,
            "provider": null,
            "sparse": true,
            "state": "present"
        }
    },
    "item": {
        "area_id": 4,
        "des": "External-Secondary",
        "interface": "Vlan99",
        "ipv4": "10.151.164.97/27",
        "pim": true
    }
}


Non-working (Eth interface):
--------------------------
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
<tc1-spinc002> attempting to start connection
<tc1-spinc002> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/local/bin/ansible-connection
<tc1-spinc002> found existing local domain socket, using it!
<tc1-spinc002> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<tc1-spinc002> updating play_context for connection
<tc1-spinc002>
<tc1-spinc002> local domain socket path is /home/jrozmus/.ansible/pc/4682c8f078
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fec55768978> for vault_id=default
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fec55768978> for vault_id=default
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
redirecting (type: action) cisco.nxos.nxos_pim_interface to cisco.nxos.nxos
<tc1-spinc002> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<tc1-spinc002> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<tc1-spinc002> ESTABLISH LOCAL CONNECTION FOR USER: jrozmus
<tc1-spinc002> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3 `"&& mkdir "` echo /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansi                                                                            ble-tmp-1656427572.2357132-4152848-91773308578837 `" && echo ansible-tmp-1656427572.2357132-4152848-91773308578837="` echo /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-16564275                                                                            72.2357132-4152848-91773308578837 `" ) && sleep 0'
Using module file /home/jrozmus/ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py
<tc1-spinc002> PUT /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/tmpcqmtep5b TO /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-9177330857883                                                                            7/AnsiballZ_nxos_pim_interface.py
<tc1-spinc002> EXEC /bin/sh -c 'chmod u+x /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/ /home/jrozmus/.ansible/tmp/ansible-local-41523                                                                            62_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_interface.py && sleep 0'
<tc1-spinc002> EXEC /bin/sh -c '/usr/libexec/platform-python /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_interface                                                                            .py && sleep 0'
<tc1-spinc002> EXEC /bin/sh -c 'rm -f -r /home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_x8yp3cpr/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 642, i                                                                            n <module>
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_x8yp3cpr/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 603, i                                                                            n main
  File "/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_x8yp3cpr/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py", line 329, i                                                                            n get_pim_interface
AttributeError: 'NoneType' object has no attribute 'group'
failed: [tc1-spinc002] (item={'interface': 'Ethernet1/39', 'ipv4': '10.4.254.52/29', 'ospf_cost': 3, 'area_id': 4, 'passive': False, 'ospf_hello': 1, 'ospf_dead': 4, 'network_type': 'broadcast', 'pim'                                                                            : True, 'bfd': 'disable', 'desc': 'ch1-firec002-e1/15'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "area_id": 4,
        "bfd": "disable",
        "desc": "ch1-firec002-e1/15",
        "interface": "Ethernet1/39",
        "ipv4": "10.4.254.52/29",
        "network_type": "broadcast",
        "ospf_cost": 3,
        "ospf_dead": 4,
        "ospf_hello": 1,
        "passive": false,
        "pim": true
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_int                                                                            erface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-4152848-91773308578837/AnsiballZ_nxos_pim_in                                                                            terface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jrozmus/.ansible/tmp/ansible-local-4152362_3hya1a3/ansible-tmp-1656427572.2357132-                                                                            4152848-91773308578837/AnsiballZ_nxos_pim_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_pim_interface', init_globals=Non                                                                            e, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/pyt                                                                            hon3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"                                                                            /tmp/ansible_cisco.nxos.nxos_pim_interface_payload_x8yp3cpr/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line 642, in <modu                                                                            le>\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_x8yp3cpr/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.py\", line                                                                             603, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_pim_interface_payload_x8yp3cpr/ansible_cisco.nxos.nxos_pim_interface_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_pim_interface.                                                                            py\", line 329, in get_pim_interface\nAttributeError: 'NoneType' object has no attribute 'group'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by feisa** [comment]
@NilashishC any update on this ?

**Comment by NilashishC** [comment]
@feisa @rozmusjs I have started looking at this bug again. Thank you for your patience.

**Comment by feisa** [comment]
@NilashishC any update?

**Comment by NilashishC** [comment]
@praveenramoorthy I could not reproduce this. Could we have another look at this together?

**Comment by praveenramoorthy** [comment]
@NilashishC sure
